# with-expecter: true
inpackage: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: True
packages:
    github.com/dmzsz/duozhuayu:
        config:
            recursive: True